language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository

script:
  # The project currently contains no android tests.
  # By default Travis-ci executes './gradlew build connectedCheck' which checks for connected devices
  - ./gradlew build
