language: android
jdk: oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.14.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - platform-tools
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-24

licenses:
    - 'android-sdk-license-c81a61d9'
    - 'android-sdk-license-.+'


script:
  - ./build.sh
